name: Test GitHub Secrets

on:
  push:
    branches:
      - main

jobs:
  print-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Echo masked secret
        run: |
          echo "The best food in the world is ${{ vars.DAT_SECRET_THO }}"
          echo "DAT_SECRET_THO is: ${{ secrets.DAT_SECRET_THO }}"
